### ISSUE TITLE
tf.reduce_sum

### ISSUE THREAD

**Issue by Errorkiller** [vlfeat/matconvnet-contrib#2]
hi,
I am very interested in your work, and I want to know how to implement 'tf.reduce_sum' in matconvnet!

**Comment by jotaf98** [comment]
Sure, if using autonn just use sum. For example to reduce the third dimension of tensor x, use sum(x, 3).

Anyway the appropriate GitHub repo is https://github.com/vlfeat/autonn .

**Comment by Errorkiller** [comment]
thank you very much!
